name: ngsolve-environment
channels:
  - conda-forge
  - pythonocc
  - ngsolve
dependencies:
  - ngsolve-nogui
  - numpy
  - matplotlib
  - scipy
  - jupyter
  - ipywidgets
  - ipympl
  - pymetis
  - sympy
  - pandas
  - prettytable
  - nbgitpuller


  
